#TIPS ANALISIS DE DATAFRAMES

##Traer el dataframe

In [ ]:
# Importamos las librerias necesarias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as py
import plotly.io as pio
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn import preprocessing
from yellowbrick.cluster import KElbowVisualizer
import warnings
import numpy as np
warnings.filterwarnings("ignore")
py.offline.init_notebook_mode(connected = True)
pio.renderers.default='browser'

In [ ]:
# Traer el CSV

df_eda = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/EDA/Datos/EDA_00.csv', sep=",", na_values=' ?')
# despues del separador podemos añadir header= None, para decir que este dataframe no tiene cabecera
# tamien podemos añadir na_values=' ?' para indicar que si encuetra ese caracter lo tome como NaN

##Opciones al traer el dataframe

Además de las opciones de separador (sep) y valores nulos (na_values) que ya estamos utilizando, el método pd.read_csv() ofrece muchas otras opciones útiles:

*    encoding: Especifica la codificación del archivo (por ejemplo, 'utf-8', 'latin-1', etc.).
    *   Ejemplo: encoding='utf-8'
*    header: Indica qué fila usar como encabezado. Usa None si no hay encabezado.
    *            Ejemplo: header=0 (por defecto, usa la primera fila)
*    names: Proporciona una lista de nombres de columnas.
    *   Ejemplo: names=['col1', 'col2', 'col3']
*    usecols: Especifica qué columnas leer, ya sea por índice o nombre.
    *   Ejemplo: usecols=[0, 1, 2] o usecols=['col1', 'col2']
*    dtype: Define tipos de datos para las columnas.
    *   Ejemplo: dtype={'col1': 'int64', 'col2': 'float64'}
*    parse_dates: Convierte columnas específicas a fechas.
    *   Ejemplo: parse_dates=['fecha']
*    skiprows: Salta un número específico de filas al principio del archivo.
    *   Ejemplo: skiprows=2
*    nrows: Lee solo un número específico de filas.
    *   Ejemplo: nrows=1000
*    index_col: Usa una columna específica como índice.
    *   Ejemplo: index_col='ID'
*    thousands: Especifica el separador de miles.
    *   Ejemplo: thousands=','
*    decimal: Especifica el separador decimal.
    *   Ejemplo: decimal='.'
*    comment: Ignora líneas que comienzan con un carácter específico.
    *   Ejemplo: comment='#'
*    skip_blank_lines: Salta líneas en blanco.
    *   Ejemplo: skip_blank_lines=True
*    low_memory: Reduce el uso de memoria al procesar el archivo por partes.
    *   Ejemplo: low_memory=False

In [ ]:
# Ejemplo aplicando alguna funcion mas

df_eda = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/EDA/Datos/EDA_01.csv',
                     sep=",",
                     na_values=' ?',
                     encoding='utf-8',
                     usecols=['col1', 'col2', 'col3'],
                     parse_dates=['fecha'],
                     thousands=',',
                     decimal='.',
                     low_memory=False)

# Este código leería el archivo CSV con codificación UTF-8,
# seleccionaría solo ciertas columnas,
# convertiría una columna a fechas,
# especificaría el separador de miles y decimal,
# usaría más memoria para procesar el archivo más rápidamente.

## Estadistica general, solo datos numericos

In [ ]:
df_eda.describe() # estadistica general

       id cliente       edad
count   58.000000  58.000000
mean    29.500000  42.327586
std     16.886879  17.496253
min      1.000000   9.000000
25%     15.250000  29.250000
50%     29.500000  40.500000
75%     43.750000  57.500000
max     58.000000  80.000000

## Info del df

In [ ]:
# Info del df
df_eda.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id cliente    58 non-null     int64
 1   nombre        58 non-null     object
 2   apellido1     58 non-null     object
 3   apellido2     58 non-null     object
 4   telefono      58 non-null     object
 5   edad          58 non-null     int64
 6   sexo          54 non-null     object
 7   estado salud  51 non-null     object
 8   ingresos      55 non-null     object
 9   deporte       55 non-null     object
 10  educacion     54 non-null     object
dtypes: int64(2), object(9)
memory usage: 5.1+ KB

##Dimensiones del df

In [ ]:
print('Dimensiones del df:', df_eda.shape)
print()

Dimensiones del df: (58, 11)

## Mostrar el encabezado (primeras 3 filas)

In [ ]:
# Mostrar el encabezado (primeras 3 filas)
print("Encabezado del dataset:")
display(df_eda.head(3))

## Mostrar 3 filas al azar

In [ ]:
# Mostrar 3 filas al azar
print("\n3 filas al azar del dataset:")
display(df_eda.sample(3))

## Mostrar la cola (últimas 3 filas)

In [ ]:
# Mostrar la cola (últimas 3 filas)
print("\nCola del dataset:")
display(df_eda.tail(3))

##Ver todo el dataframe de forma mas estetica

In [ ]:
# Ver todo el dataframe de forma mas estetica
display(df_eda)

,id cliente,nombre,apellido1,apellido2,telefono,edad,sexo,estado salud,ingresos,deporte,educacion
0,1,Alejandro,García,Navarro,631 456 789,9,hombre,Malo,Bajo,Sí,Secundaria
1,2,Mariana,Rodríguez,Reyes,55 1234 5678,22,mujer,Normal,Medio,No,Primaria
2,3,Carlos,Martínez,Romero,213 987 6543,25,hombre,Excelente,Alto,Sí,Universitaria
3,4,Sofía,López,Vargas,7911 123456,27,mujer,Normal,Bajo,No,Postgrado
4,5,David,Hernández,Domínguez,176 5432 1098,30,NaN,NaN,Medio,Sí,Secundaria
5,6,Valeria,Pérez,Silva,6 12 34 56 78,32,NaN,Malo,Bajo,No,Primaria
6,7,Juan,González,Serrano,412 345 678,35,hombre,Normal,Alto,Sí,Universitaria
7,8,Gabriela,Sánchez,Paredes,678 901 234,37,mujer,Excelente,Medio,No,Secundaria
8,9,Fernando,Ramírez,Méndez,81 2345 6789,40,hombre,Normal,Bajo,Sí,Postgrado
9,10,Isabel,Torres,Castro,917 765 4321,43,mujer,Malo,Medio,NaN,Primaria
10,11,Luis,Flores,Rojas,7812 987654,46,hombre,NaN,Alto,Sí,Universitaria
11,12,Camila,Cruz,Peña,622 111 222,48,mujer,Malo,Bajo,No,Secundaria
12,13,Ricardo,Rivera,Acosta,151 234 56789,51,hombre,Excelente,NaN,Sí,Primaria
13,14,Daniela,Morales,Montes,7 89 01 23 45,54,mujer,Malo,Bajo,No,Postgrado
14,15,Pablo,Ortiz,Figueroa,33 3456 7890,56,hombre,Normal,Alto,Sí,Universitaria
15,16,Lucía,Castillo,Vega,612 345 678,58,mujer,Malo,Medio,No,NaN
16,17,Miguel,Ramos,Salinas,415 987 1234,61,hombre,Malo,Bajo,Sí,Primaria
17,18,Andrea,Gutiérrez,Esquivel,7423 876543,63,mujer,NaN,Alto,No,Postgrado
18,19,José,Jiménez,Lara,490 765 432,64,NaN,Excelente,Medio,Sí,Universitaria
19,20,Patricia,Mendoza,Ponce,55 5678 1234,65,mujer,Malo,Bajo,No,Secundaria
20,21,Roberto,de todos los santos,gutierrez,620 888 888,40,NaN,Malo,Alto,Sí,Primaria
21,22,Ricardo,Rivera,Acosta,151 234 56789,51,hombre,Normal,Medio,No,Postgrado
22,23,Alejandro,García,Navarro,631 456 789,9,hombre,Malo,Bajo,Sí,Universitaria
23,24,Mariana,Rodríguez,Reyes,55 1234 5678,22,mujer,Excelente,Medio,No,Secundaria
24,25,Carlos,Martínez,Romero,213 987 6543,25,hombre,Malo,NaN,Sí,Primaria
25,26,Rodrigo,García,Mendizábal,672 345 789,27,hombre,Excelente,Bajo,No,Universitaria
26,51,Ricardo,Rivera,Acosta,151 234 56789,51,hombre,Excelente,Medio,Sí,Primaria
27,27,Natalia,Fernández,Uribe,601 234 567,64,mujer,Malo,Medio,Sí,Secundaria
28,28,Esteban,González,Sanz,689 987 654,35,hombre,Malo,Alto,No,Postgrado
29,29,Isabel,Martínez,Salazar,612 345 678,18,mujer,NaN,Bajo,Sí,NaN
30,30,Hugo,López,Aguirre,673 890 123,52,hombre,Malo,Medio,No,Universitaria
31,31,Fernanda,Pérez,Etxebarria,645 321 098,71,mujer,Otro,Alto,Sí,Secundaria
32,32,Enrique,Sánchez,Aramburu,687 654 321,29,hombre,Malo,Bajo,No,Primaria
33,33,Elena,Álvarez,Sarasola,609 876 543,47,mujer,Otro,Medio,Sí,Postgrado
34,34,Manuel,Gutiérrez,Zabaleta,611 123 456,15,hombre,NaN,Alto,No,Universitaria
35,35,Julia,Rodríguez,Ochoa,658 765 432,38,mujer,Excelente,Bajo,Sí,Secundaria
36,36,Sebastián,Muñoz,Garmendia,621 456 789,23,hombre,Malo,Medio,No,Primaria
37,37,Claudia,Díez,Urrutia,654 987 321,60,mujer,Malo,Alto,Sí,Postgrado
38,38,Francisco,Alonso,Aznar,677 890 654,76,hombre,NaN,Bajo,No,Universitaria
39,39,Beatriz,Gómez,Goikoetxea,645 098 765,55,mujer,Normal,Medio,Sí,Secundaria
40,52,Patricia,Mendoza,Ponce,55 5678 1234,65,mujer,Malo,Bajo,NaN,Secundaria
41,40,Rubén,Ortega,Olazábal,683 567 123,19,hombre,Excelente,Alto,NaN,NaN
42,41,Alicia,Ruiz,Unzueta,699 234 890,41,mujer,Malo,Bajo,Sí,Universitaria
43,42,Óscar,Villar,Eguía,615 876 543,30,hombre,Malo,Medio,No,Secundaria
44,43,Irene,Llorente,Bedia,647 890 321,66,mujer,Normal,NaN,Sí,Postgrado
45,44,Pedro,Echeverría,Iturralde,633 098 765,25,hombre,Excelente,Bajo,No,Primaria
46,45,Marta,Zubizarreta,Bermejo,622 123 789,49,mujer,Malo,Medio,Sí,Universitaria
47,46,Álvaro,Ibarra,Iribarren,609 456 123,80,hombre,NaN,Alto,No,Secundaria
48,47,Mónica,Otegui,Lizarazu,675 321 987,33,mujer,Malo,Bajo,Sí,Primaria
49,48,Rafael,Goñi,Olano,692 654 321,44,hombre,Normal,Medio,No,Postgrado
50,49,Susana,Arrieta,Aizpurua,687 234 567,58,mujer,Otro,Alto,Sí,Universitaria
51,50,Cristian,Arozena,Iriarte,611 987 654,16,hombre,Malo,Bajo,No,Secundaria
52,53,Claudia,Díez,Urrutia,654 987 321,60,mujer,Malo,Alto,Sí,NaN
53,54,Lucía,Castillo,Vega,612 345 678,58,mujer,Malo,Medio,No,Secundaria
54,55,Julia,Rodríguez,Ochoa,658 765 432,38,mujer,Excelente,Bajo,Sí,Secundaria
55,56,Mónica,Otegui,Lizarazu,675 321 987,33,mujer,Malo,Bajo,Sí,Primaria
56,57,Mónica,Otegui,Lizarazu,675 321 987,33,mujer,Malo,Bajo,Sí,Primaria
57,58,Mónica,Otegui,Lizarazu,675 321 987,33,mujer,Malo,Bajo,Sí,Primaria

## Mostrar las cabeceras del DataFrame

In [ ]:
# Mostrar las cabeceras del DataFrame
print(df_eda.columns)
print()
# Convertir a lista y mostrar
cabeceras = df_eda.columns.tolist()
print(cabeceras)

Index(['id cliente', 'nombre', 'apellido1', 'apellido2', 'telefono', 'edad',
       'sexo', 'estado salud', 'ingresos', 'deporte', 'educacion'],
      dtype='object')

['id cliente', 'nombre', 'apellido1', 'apellido2', 'telefono', 'edad', 'sexo', 'estado salud', 'ingresos', 'deporte', 'educacion']

##Resumen del número de valores faltantes (NaN)

In [ ]:
df_eda.isna().sum()
# El comando df_eda.isna().sum() te devuelve un resumen del número de valores faltantes (NaN) en cada columna de tu DataFrame df_eda.

id cliente      0
nombre          0
apellido1       0
apellido2       0
telefono        0
edad            0
sexo            4
estado salud    7
ingresos        3
deporte         3
educacion       4
dtype: int64

## Ver las subcategorias de las columnas

Se pueden observar todas las subcategorias de las columnas de tipo Object y category

O sea, los que tienen string.

Es muy util ya que en una columna puedes observar si existen categorias diferentes a las esperadas, como por ejemplo:
*   hombre, mujer, NaN. Al ver el NaN sabes que hay faltantes.
*   Si, No, ?, de esta forma ves que hay algun caracter extraño.
*   Sí, Si, si, No, no, de esta forma ves falos tipograficos
*   Telefono, Telfno., Tel., Celular, Teléfono. Tambien ves fallos tipograficos y formas de decir lo mismo

In [ ]:
# Ver las subcategorias de las columnas
categorical_columns = df_eda.select_dtypes(include=['object', 'category']).columns

for col in categorical_columns:
    print(f"Subcategorías de la columna '{col}':")
    print(df_eda[col].unique())
    print("\n")

Subcategorías de la columna 'nombre':
['Alejandro' 'Mariana' 'Carlos' 'Sofía' 'David' 'Valeria' 'Juan'
 'Gabriela' 'Fernando' 'Isabel' 'Luis' 'Camila' 'Ricardo' 'Daniela'
 'Pablo' 'Lucía' 'Miguel' 'Andrea' 'José' 'Patricia' 'Roberto' 'Rodrigo'
 'Natalia' 'Esteban' 'Hugo' 'Fernanda' 'Enrique' 'Elena' 'Manuel' 'Julia'
 'Sebastián' 'Claudia' 'Francisco' 'Beatriz' 'Rubén' 'Alicia' 'Óscar'
 'Irene' 'Pedro' 'Marta' 'Álvaro' 'Mónica' 'Rafael' 'Susana' 'Cristian']


Subcategorías de la columna 'apellido1':
['García' 'Rodríguez' 'Martínez' 'López' 'Hernández' 'Pérez' 'González'
 'Sánchez' 'Ramírez' 'Torres' 'Flores' 'Cruz' 'Rivera' 'Morales' 'Ortiz'
 'Castillo' 'Ramos' 'Gutiérrez' 'Jiménez' 'Mendoza' 'de todos los santos'
 'Fernández' 'Álvarez' 'Muñoz' 'Díez' 'Alonso' 'Gómez' 'Ortega' 'Ruiz'
 'Villar' 'Llorente' 'Echeverría' 'Zubizarreta' 'Ibarra' 'Otegui' 'Goñi'
 'Arrieta' 'Arozena']


Subcategorías de la columna 'apellido2':
['Navarro' 'Reyes' 'Romero' 'Vargas' 'Domínguez' 'Silva' 'Serrano'
 'Paredes' 'Méndez' 'Castro' 'Rojas' 'Peña' 'Acosta' 'Montes' 'Figueroa'
 'Vega' 'Salinas' 'Esquivel' 'Lara' 'Ponce' 'gutierrez' 'Mendizábal'
 'Uribe' 'Sanz' 'Salazar' 'Aguirre' 'Etxebarria' 'Aramburu' 'Sarasola'
 'Zabaleta' 'Ochoa' 'Garmendia' 'Urrutia' 'Aznar' 'Goikoetxea' 'Olazábal'
 'Unzueta' 'Eguía' 'Bedia' 'Iturralde' 'Bermejo' 'Iribarren' 'Lizarazu'
 'Olano' 'Aizpurua' 'Iriarte']


Subcategorías de la columna 'telefono':
['631 456 789' '55 1234 5678' '213 987 6543' '7911 123456' '176 5432 1098'
 '6 12 34 56 78' '412 345 678' '678 901 234' '81 2345 6789' '917 765 4321'
 '7812 987654' '622 111 222' '151 234 56789' '7 89 01 23 45'
 '33 3456 7890' '612 345 678' '415 987 1234' '7423 876543' '490 765 432'
 '55 5678 1234' '620 888 888' '672 345 789' '601 234 567' '689 987 654'
 '673 890 123' '645 321 098' '687 654 321' '609 876 543' '611 123 456'
 '658 765 432' '621 456 789' '654 987 321' '677 890 654' '645 098 765'
 '683 567 123' '699 234 890' '615 876 543' '647 890 321' '633 098 765'
 '622 123 789' '609 456 123' '675 321 987' '692 654 321' '687 234 567'
 '611 987 654']


Subcategorías de la columna 'sexo':
['hombre' 'mujer' nan]


Subcategorías de la columna 'estado salud':
['Malo' 'Normal' 'Excelente' nan 'Otro']


Subcategorías de la columna 'ingresos':
['Bajo' 'Medio' 'Alto' nan]


Subcategorías de la columna 'deporte':
['Sí' 'No' nan]


Subcategorías de la columna 'educacion':
['Secundaria' 'Primaria' 'Universitaria' 'Postgrado' nan]

## Para ver subcategorias de las columnas seleccionadas

In [ ]:
# # Ver las subcategorias de las columnas

# Lista de columnas específicas que quieres inspeccionar
columnas_especificas = ['educacion', 'ingresos', 'sexo']  # solo con string
# tambien funciona con nuemros, pero si la lista es larga y son todos diferentes...

# Iterar sobre cada columna y mostrar sus subcategorías
for col in columnas_especificas:
    if col in df_eda.columns:  # Verifica si la columna existe en el DataFrame
        print(f"Subcategorías de la columna '{col}':")
        print(df_eda[col].unique())
        print("\n")
    else:
        print(f"La columna '{col}' no existe en el DataFrame.")

Subcategorías de la columna 'educacion':
['Secundaria' 'Primaria' 'Universitaria' 'Postgrado' nan]


Subcategorías de la columna 'ingresos':
['Bajo' 'Medio' 'Alto' nan]


Subcategorías de la columna 'sexo':
['hombre' 'mujer' nan]

## Para ver subcategorias de las columnas seleccionadas y contar cantidades

In [ ]:
# Lista de columnas específicas que quieres inspeccionar
columnas_especificas = ['educacion', 'ingresos', 'sexo']  # solo con string
# tambien funciona con nuemros, pero si la lista es larga y son todos diferentes...

# Iterar sobre cada columna y mostrar sus subcategorías junto con el conteo
for col in columnas_especificas:
    if col in df_eda.columns:  # Verifica si la columna existe en el DataFrame
        print(f"Subcategorías de la columna '{col}' con su conteo:")
        print(df_eda[col].value_counts())
        print("\n")
    else:
        print(f"La columna '{col}' no existe en el DataFrame.")

Subcategorías de la columna 'educacion' con su conteo:
educacion
Secundaria       16
Primaria         15
Universitaria    13
Postgrado        10
Name: count, dtype: int64


Subcategorías de la columna 'ingresos' con su conteo:
ingresos
Bajo     23
Medio    18
Alto     14
Name: count, dtype: int64


Subcategorías de la columna 'sexo' con su conteo:
sexo
mujer     29
hombre    25
Name: count, dtype: int64

## Ver valores numericos por rangos

In [ ]:
# Ver valores numericos por rangos
df_eda['Edad_rango'] = pd.cut(df_eda['edad'], bins=[0, 20, 30, 40, 50, 60])
print(df_eda['Edad_rango'].value_counts())

Edad_rango
(30, 40]    12
(50, 60]    12
(20, 30]    11
(40, 50]     7
(0, 20]      6
Name: count, dtype: int64

##Para calcular el sesgo y la curtosis solo numericas

In [ ]:
# Lista de columnas específicas
columnas_especificas = ['edad']  # solo con numericas

# Verificar si las columnas existen en el DataFrame y calcular el sesgo y la curtosis
sesgo = df_eda[columnas_especificas].skew()
curtosis = df_eda[columnas_especificas].kurt()

print("Sesgo de las columnas específicas:")
print(sesgo)
print("\nCurtosis de las columnas específicas:")
print(curtosis)

Sesgo de las columnas específicas:
edad    0.073134
dtype: float64

Curtosis de las columnas específicas:
edad   -0.837271
dtype: float64

##Para calcular el sesgo y la curtosis solo numericas

In [ ]:
# Lista de columnas específicas
columnas_especificas = ['educacion', 'ingresos', 'sexo', 'edad']  # aqui cualquier tipo

# Filtrar columnas que sean numéricas
columnas_numericas = df_eda[columnas_especificas].select_dtypes(include=['number']).columns

# Calcular sesgo y curtosis solo en columnas numéricas
sesgo = df_eda[columnas_numericas].skew()
curtosis = df_eda[columnas_numericas].kurt()

print("Sesgo de las columnas numéricas específicas:")
print(sesgo)
print("\nCurtosis de las columnas numéricas específicas:")
print(curtosis)

Sesgo de las columnas numéricas específicas:
edad    0.073134
dtype: float64

Curtosis de las columnas numéricas específicas:
edad   -0.837271
dtype: float64

##Para calcular el sesgo y la curtosis cualquier tipo Object y Numerica

In [ ]:
# Lista de columnas específicas
columnas_especificas = ['educacion', 'ingresos', 'sexo', 'edad']  # aqui cualquier tipo

# Convertir las columnas categóricas a variables dummy
df_dummies = pd.get_dummies(df_eda[columnas_especificas])

# Calcular el sesgo y la curtosis en las columnas dummy
sesgo = df_dummies.skew()
curtosis = df_dummies.kurt()

print("Sesgo de las columnas categóricas (variables dummy):")
print(sesgo)
print("\nCurtosis de las columnas categóricas (variables dummy):")
print(curtosis)

Sesgo de las columnas categóricas (variables dummy):
edad                       0.073134
educacion_Postgrado        1.780846
educacion_Primaria         1.131987
educacion_Secundaria       1.029798
educacion_Universitaria    1.358424
ingresos_Alto              1.241064
ingresos_Bajo              0.434257
ingresos_Medio             0.841821
sexo_hombre                0.285974
sexo_mujer                 0.000000
dtype: float64

Curtosis de las columnas categóricas (variables dummy):
edad                      -0.837271
educacion_Postgrado        1.212021
educacion_Primaria        -0.745539
educacion_Secundaria      -0.974345
educacion_Universitaria   -0.161465
ingresos_Alto             -0.477443
ingresos_Bajo             -1.877409
ingresos_Medio            -1.338739
sexo_hombre               -1.988024
sexo_mujer                -2.072727
dtype: float64

In [ ]:
df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   edad                     58 non-null     int64
 1   educacion_Postgrado      58 non-null     bool
 2   educacion_Primaria       58 non-null     bool
 3   educacion_Secundaria     58 non-null     bool
 4   educacion_Universitaria  58 non-null     bool
 5   ingresos_Alto            58 non-null     bool
 6   ingresos_Bajo            58 non-null     bool
 7   ingresos_Medio           58 non-null     bool
 8   sexo_hombre              58 non-null     bool
 9   sexo_mujer               58 non-null     bool
dtypes: bool(9), int64(1)
memory usage: 1.1 KB

##Otras utilidades

In [ ]:
# Detectar si una cadena contiene cierto valor
df_eda['columna1'].str.contains('patron')

# Contar cuántas veces aparece un carácter o subcadena
df_eda['columna1'].str.count('a')

# Convertir a mayúsculas o minúsculas
df_eda['columna1'] = df_eda['columna1'].str.lower()

# Remover espacios
df_eda['columna1'] = df_eda['columna1'].str.strip()

# Reemplazar valores en una columna categórica
df_eda['columna1'] = df_eda['columna1'].replace({'valor_incorrecto': 'valor_correcto'})

# Filtrar filas donde una columna tenga cierto valor
df_filtrado = df_eda.query('columna1 == "valor_deseado"')

# Crear una tabla dinámica que muestre la media de una columna numérica para cada categoría
pd.pivot_table(df_eda, values='columna_numerica', index='columna_categorica', aggfunc='mean')

# Crear una tabla cruzada para dos columnas categóricas
pd.crosstab(df_eda['columna1'], df_eda['columna2'])